#! /bin/sh

if [ "$#" != "1" ]; then
    echo usage: config 'cygwin|linux';
    exit 1;
fi

if [ ! -d "$1" ]; then
    echo error: \'$1\' is not a valid configuration;
    exit 2;
fi

rm -f Makefile.build.local Makefile.config.local
if ls $1/Makefile.* >/dev/null 2>&1; then
    for f in $1/Makefile.*; do
        ln -sf $f .
    done
fi
exit 0
